# DESABILITADO MANUALMENTE EN EL REPOSITORIO GITHUB ACTIONS
name: Docker Build and Publish

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build and package with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t seiler18/mascachicles:latest .

    - name: Push Docker image
      run: docker push seiler18/mascachicles:latest

    - name: Run Docker container
      run: docker run -d -p 8081:8081 seiler18/mascachicles:latest

    - name: Wait for application to start
      run: sleep 15  # Ajusta esto según cuánto tiempo toma tu aplicación en arrancar

    - name: Verify application is running
      run: curl -Is http://localhost:8081/actuator/health | head -n 1 | grep 200

    - name: Clean up Docker containers
      run: docker ps -q --filter ancestor=seiler18/mascachicles:latest | xargs -r docker stop
